









#include "elements.h"
// the information in this file was taken from the "Winamp 2.X skinnig tutorial" Version 1.5.0, copyright by Fyre

const tElements elements[]={
// from avs.bmp
	{.filename="avs.bmp",	.startx=   0,.starty=   0,.dimx=  0,.dimy=  0,.id=AVS_CLOSE_BUTTON_PRESSED},
	{.filename="avs.bmp",	.startx=  15,.starty=   0,.dimx= 50,.dimy= 15,.id=AVS_UPPER_LEFT_CORNER},
	{.filename="avs.bmp",	.startx=  66,.starty=  15,.dimx= 14,.dimy= 15,.id=AVS_TOP_FILLER},
	{.filename="avs.bmp",	.startx=  81,.starty=   0,.dimx= 16,.dimy= 15,.id=AVS_UPPER_RIGHT_CORNER},
	{.filename="avs.bmp",	.startx=   0,.starty=  16,.dimx=  7,.dimy=172,.id=AVS_LEFT_FILLER},
	{.filename="avs.bmp",	.startx=   8,.starty=  16,.dimx=  6,.dimy=172,.id=AVS_RIGHT_FILLER},
	{.filename="avs.bmp",	.startx=  15,.starty=  16,.dimx= 50,.dimy=  5,.id=AVS_LOWER_LEFT_CORNER},
	{.filename="avs.bmp",	.startx=  66,.starty=  16,.dimx= 14,.dimy=  5,.id=AVS_BOTTOM_FILLER},
	{.filename="avs.bmp",	.startx=  81,.starty=  16,.dimx= 16,.dimy=  5,.id=AVS_LOWER_RIGHT_CORNER},

// from balance.bmp
	{.filename="balance.bmp",.startx=    9,.starty=    0,.dimx= 38,.dimy= 13,.id=BALANCE_CENTERED},
	{.filename="balance.bmp",.startx=    9,.starty=   15,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER0},
	{.filename="balance.bmp",.startx=    9,.starty=   30,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER1},
	{.filename="balance.bmp",.startx=    9,.starty=   45,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER2},
	{.filename="balance.bmp",.startx=    9,.starty=   60,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER3},
	{.filename="balance.bmp",.startx=    9,.starty=   75,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER4},
	{.filename="balance.bmp",.startx=    9,.starty=   90,.dimx= 38,.dimy= 13,.id=BALANCE_24LEFTORRIGHT},
	{.filename="balance.bmp",.startx=    9,.starty=  105,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER5},
	{.filename="balance.bmp",.startx=    9,.starty=  120,.dimx= 38,.dimy= 13,.id=BALANCE_33LEFTORRIGHT},
	{.filename="balance.bmp",.startx=    9,.starty=  135,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER6},
	{.filename="balance.bmp",.startx=    9,.starty=  150,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER7},	
	{.filename="balance.bmp",.startx=    9,.starty=  165,.dimx= 38,.dimy= 13,.id=BALANCE_40LEFTORRIGHT},
	{.filename="balance.bmp",.startx=    9,.starty=  180,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER8},
	{.filename="balance.bmp",.startx=    9,.starty=  195,.dimx= 38,.dimy= 13,.id=BALANCE_49LEFTORRIGHT},
	{.filename="balance.bmp",.startx=    9,.starty=  210,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER9},
	{.filename="balance.bmp",.startx=    9,.starty=  225,.dimx= 38,.dimy= 13,.id=BALANCE_58LEFTORRIGHT},
	{.filename="balance.bmp",.startx=    9,.starty=  240,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER10},
	{.filename="balance.bmp",.startx=    9,.starty=  255,.dimx= 38,.dimy= 13,.id=BALANCE_66LEFTORRIGHT},
	{.filename="balance.bmp",.startx=    9,.starty=  270,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER11},
	{.filename="balance.bmp",.startx=    9,.starty=  285,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER12},
	{.filename="balance.bmp",.startx=    9,.starty=  300,.dimx= 38,.dimy= 13,.id=BALANCE_74LEFTORRIGHT},
	{.filename="balance.bmp",.startx=    9,.starty=  315,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER13},
	{.filename="balance.bmp",.startx=    9,.starty=  330,.dimx= 38,.dimy= 13,.id=BALANCE_82LEFTORRIGHT},
	{.filename="balance.bmp",.startx=    9,.starty=  345,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER14},
	{.filename="balance.bmp",.startx=    9,.starty=  360,.dimx= 38,.dimy= 13,.id=BALANCE_91LEFTORRIGHT},
	{.filename="balance.bmp",.startx=    9,.starty=  375,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER15},
	{.filename="balance.bmp",.startx=    9,.starty=  390,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER16},
	{.filename="balance.bmp",.startx=    9,.starty=  405,.dimx= 38,.dimy= 13,.id=BALANCE_100LEFTORRIGHT},
	{.filename="balance.bmp",.startx=    0,.starty=  422,.dimx= 14,.dimy= 11,.id=BALANCE_SLIDER_PRESSED},
	{.filename="balance.bmp",.startx=   15,.starty=  422,.dimx= 14,.dimy= 11,.id=BALANCE_SLIDER_UNPRESSED},

// from cbuttons.bmp
	{.filename="cbuttons.bmp",.startx=    0,.starty=    0,.dimx= 23,.dimy= 18,.id=CBUTTONS_PREV_BUTTON_UNPRESSED},
	{.filename="cbuttons.bmp",.startx=   23,.starty=    0,.dimx= 23,.dimy= 18,.id=CBUTTONS_PLAY_BUTTON_UNPRESSED},
	{.filename="cbuttons.bmp",.startx=   46,.starty=    0,.dimx= 23,.dimy= 18,.id=CBUTTONS_PAUSE_BUTTON_UNPRESSED},
	{.filename="cbuttons.bmp",.startx=   69,.starty=    0,.dimx= 23,.dimy= 18,.id=CBUTTONS_STOP_BUTTON_UNPRESSED},
	{.filename="cbuttons.bmp",.startx=   92,.starty=    0,.dimx= 22,.dimy= 18,.id=CBUTTONS_NEXT_BUTTON_UNPRESSED},
	{.filename="cbuttons.bmp",.startx=  114,.starty=    0,.dimx= 22,.dimy= 16,.id=CBUTTONS_OPEN_BUTTON_UNPRESSED},
	{.filename="cbuttons.bmp",.startx=    0,.starty=   18,.dimx= 23,.dimy= 18,.id=CBUTTONS_PREV_BUTTON_PRESSED},
	{.filename="cbuttons.bmp",.startx=   23,.starty=   18,.dimx= 23,.dimy= 18,.id=CBUTTONS_PLAY_BUTTON_PRESSED},
	{.filename="cbuttons.bmp",.startx=   46,.starty=   18,.dimx= 23,.dimy= 18,.id=CBUTTONS_PAUSE_BUTTON_PRESSED},
	{.filename="cbuttons.bmp",.startx=   69,.starty=   18,.dimx= 23,.dimy= 18,.id=CBUTTONS_STOP_BUTTON_PRESSED},
	{.filename="cbuttons.bmp",.startx=   92,.starty=   18,.dimx= 22,.dimy= 18,.id=CBUTTONS_NEXT_BUTTON_PRESSED},
	{.filename="cbuttons.bmp",.startx=  114,.starty=   18,.dimx= 22,.dimy= 16,.id=CBUTTONS_OPEN_BUTTON_PRESSED},

// from eq_ex.bmp	
	{.filename="eq_ex.bmp",   .startx=    0,.starty=    0,.dimx=275,.dimy= 14,.id=EQEX_EQUALIZER_WINDOWSHADE_ACTIVE},
	{.filename="eq_ex.bmp",   .startx=   61,.starty=    4,.dimx= 97,.dimy=  7,.id=EQEX_VOLUMECONTROL_ACTIVE},
	{.filename="eq_ex.bmp",   .startx=  164,.starty=    4,.dimx= 42,.dimy=  7,.id=EQEX_BALANCECONTROL_ACTIVE},
	{.filename="eq_ex.bmp",   .startx=    0,.starty=   15,.dimx=275,.dimy= 14,.id=EQEX_EQUALIZER_WINDOWSHADE_INACTIVE},
	{.filename="eq_ex.bmp",   .startx=   61,.starty=   19,.dimx= 97,.dimy=  7,.id=EQEX_VOLUMECONTROL_INACTIVE},
	{.filename="eq_ex.bmp",   .startx=  164,.starty=   19,.dimx= 42,.dimy=  7,.id=EQEX_BALANCECONTROL_INACTIVE},
	{.filename="eq_ex.bmp",   .startx=    1,.starty=   30,.dimx=  3,.dimy=  7,.id=EQEX_VOLUMESLIDER_LOW},
	{.filename="eq_ex.bmp",   .startx=    4,.starty=   30,.dimx=  3,.dimy=  7,.id=EQEX_VOLUMESLIDER_MEDIUM},
	{.filename="eq_ex.bmp",   .startx=    7,.starty=   30,.dimx=  3,.dimy=  7,.id=EQEX_VOLUMESLIDER_HIGH},
	{.filename="eq_ex.bmp",   .startx=   11,.starty=   30,.dimx=  3,.dimy=  7,.id=EQEX_BALANCESLIDER_LEFT},
	{.filename="eq_ex.bmp",   .startx=   14,.starty=   30,.dimx=  3,.dimy=  7,.id=EQEX_BALANCESLIDER_MIDDLE},
	{.filename="eq_ex.bmp",   .startx=   17,.starty=   30,.dimx=  3,.dimy=  7,.id=EQEX_BALANCESLIDER_RIGHT},
	{.filename="eq_ex.bmp",   .startx=    1,.starty=   38,.dimx=  9,.dimy=  9,.id=EQEX_WINDOWSHADE_BUTTON_PRESSED},
	{.filename="eq_ex.bmp",   .startx=   11,.starty=   38,.dimx=  9,.dimy=  9,.id=EQEX_CLOSEBUTTON_UNPRESSED},
	{.filename="eq_ex.bmp",   .startx=    1,.starty=   47,.dimx=  9,.dimy=  9,.id=EQEX_MAXIMIZEBUTTON_PRESSED},
	{.filename="eq_ex.bmp",   .startx=   11,.starty=   47,.dimx=  9,.dimy=  9,.id=EQEX_CLOSEBUTTON_PRESSED},

// from eqmain.bmp
	{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=275,.dimy= 14,.id=EQMAIN_EQUALIZER_TITLEBAR},
	{.filename="eqmain.bmp",  .startx=    0,.starty=   14,.dimx=275,.dimy=102,.id=EQMAIN_EQUALIZER_MAIN_DISPLAY},
	{.filename="eqmain.bmp",  .startx=   86,.starty=   16,.dimx=113,.dimy= 20,.id=EQMAIN_EQUALIZER_MINIDISPLAY},
	{.filename="eqmain.bmp",  .startx=   14,.starty=   18,.dimx= 25,.dimy= 12,.id=EQMAIN_EQUALIZER_ON},
	{.filename="eqmain.bmp",  .startx=   39,.starty=   18,.dimx= 33,.dimy= 12,.id=EQMAIN_AUTOMATIC_EQUALIZATION},
	{.filename="eqmain.bmp",  .startx=  217,.starty=   18,.dimx= 44,.dimy= 12,.id=EQMAIN_OPEN_PRESET_MENU},
	{.filename="eqmain.bmp",  .startx=   42,.starty=   33,.dimx= 26,.dimy= 10,.id=EQMAIN_20DB_RESET},
	{.filename="eqmain.bmp",  .startx=   21,.starty=   38,.dimx= 14,.dimy= 63,.id=EQMAIN_PREAMP_BAR},
	{.filename="eqmain.bmp",  .startx=   78,.starty=   38,.dimx= 14,.dimy= 63,.id=EQMAIN_60HZ_BAR},
	{.filename="eqmain.bmp",  .startx=   96,.starty=   38,.dimx= 14,.dimy= 63,.id=EQMAIN_170HZ_BAR},
	{.filename="eqmain.bmp",  .startx=  114,.starty=   38,.dimx= 14,.dimy= 63,.id=EQMAIN_310HZ_BAR},
	{.filename="eqmain.bmp",  .startx=  132,.starty=   38,.dimx= 14,.dimy= 63,.id=EQMAIN_600HZ_BAR},
	{.filename="eqmain.bmp",  .startx=  150,.starty=   38,.dimx= 14,.dimy= 63,.id=EQMAIN_1KHZ_BAR},
	{.filename="eqmain.bmp",  .startx=  168,.starty=   38,.dimx= 14,.dimy= 63,.id=EQMAIN_3KHZ_BAR},
	{.filename="eqmain.bmp",  .startx=  186,.starty=   38,.dimx= 14,.dimy= 63,.id=EQMAIN_6KHZ_BAR},
	{.filename="eqmain.bmp",  .startx=  204,.starty=   38,.dimx= 14,.dimy= 63,.id=EQMAIN_12KHZ_BAR},
	{.filename="eqmain.bmp",  .startx=  222,.starty=   38,.dimx= 14,.dimy= 63,.id=EQMAIN_14KHZ_BAR},
	{.filename="eqmain.bmp",  .startx=  240,.starty=   38,.dimx= 14,.dimy= 63,.id=EQMAIN_16KHZ_BAR},
	{.filename="eqmain.bmp",  .startx=   42,.starty=   65,.dimx= 26,.dimy= 10,.id=EQMAIN_0DB_RESET},
	{.filename="eqmain.bmp",  .startx=   42,.starty=   92,.dimx= 26,.dimy= 10,.id=EQMAIN_M20DB_RESET},
	{.filename="eqmain.bmp",  .startx=    0,.starty=  116,.dimx=  9,.dimy=  9,.id=EQMAIN_CLOSE_BUTTON_UNPRESSED},
	{.filename="eqmain.bmp",  .startx=   10,.starty=  119,.dimx= 25,.dimy= 12,.id=EQMAIN_EQUALIZER_OFF_UNPRESSED},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_AUTO_OFF_UNPRESSED},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_EQUALIZER_ON_UNPRESSED},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_AUTO_ON_UNPRESSED},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_EQUALIZER_OFF_PRESSED},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_AUTO_OFF_PRESSED},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_EQUALIZER_ON_PRESSED},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_AUTO_ON_PRESSED},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_CLOSE_BUTTON_PRESSED},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_EQUALIZER_TITLEBAR_ACTIVE},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_EQUALIZER_SLIDER_UNPRESSED},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_M2000DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_M1875DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_M1714DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_M1571DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_M1429DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_M1286DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_M1143DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_M1000DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_M0857DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_M0714DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_M0571DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_M0428DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_M0285DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_M0142DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_PRESET_BUTTON_UNPRESSED},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_EQUALIZER_SLIDER_PRESSED},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_PRESET_BUTTON_PRESSED},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_P0142DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_P0285DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_P0428DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_P0571DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_P0714DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_P0857DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_P1000DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_P1143DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_P1286DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_P1429DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_P1571DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_P1714DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_P1857DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_P2000DB_BAR},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_ACTUAL_EQUALIZER_MINIDISPLAY},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_SPLINE_LINE},
{.filename="eqmain.bmp",  .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=EQMAIN_PREAMP_LINE},

// from main.bmp
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MAIN_MAIN_DISPLAY},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MAIN_SONG_INFO_DISPLAY},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MAIN_KBPS_DISPLAY},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MAIN_KHZ_DISPLAY},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MAIN_VISUALIZATION_WINDOW},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MAIN_INFO},

// from mb (minibrowser)
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_UPPER_LEFT_CORNERPIECE_ACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_TITLEBAR_ACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_TOP_FILLERS_ACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_UPPER_RIGHT_CORNERPIECE_ACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_UPPER_LEFT_CORNERPIECE_INACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_TITLEBAR_INACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_TOPFILLERS_INACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_UPPER_RIGHT_CORNERPIECE_INACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_BOTTOM_LEFT_CONTROLBAR},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_LEFT_SIDE_FILLERS},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_RIGHT_SIDE_FILLERS},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_CLOSE_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_BACK_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_FORWARD_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_STOP_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_RELOAD_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_OPTIONS_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_BACK_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_FORWARD_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_STOP_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_RELOAD_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_OPTIONS_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_URL_DISPLAY_BAR_LEFT_END},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_BOTTOM_RIGHT_CONTROL_BAR},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_BOTTOM_FILLER},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_URL_DISPLAY_BAR_RIGHT_END},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_DISPLAY_BAR_FILLER},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MB_RESIZE_CONTROL},

// from monoster.bmp
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MONOSTER_STEREO_ACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MONOSTER_MONO_ACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MONOSTER_STEREO_INACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=MONOSTER_MONO_INACTIVE},

// from numbers.bmp
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=NUMBERS_0},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=NUMBERS_1},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=NUMBERS_2},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=NUMBERS_3},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=NUMBERS_4},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=NUMBERS_5},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=NUMBERS_6},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=NUMBERS_7},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=NUMBERS_8},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=NUMBERS_9},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=NUMBERS_BLANK},

// from playpause.bmp
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLAYPAUSE_PLAY_INDICATOR},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLAYPAUSE_PAUSE_INDICATOR},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLAYPAUSE_STOP_INDICATOR},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLAYPAUSE_FILLER},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLAYPAUSE_START_OF_SONG_INDICATOR},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLAYPAUSE_END_OF_SONG_INDICATOR},

// from pledit.bmp
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_UPPER_LEFT_CORNERPIECE_ACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_PLAYLIST_TITLEBAR_ACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_TOP_FILLERS_ACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_UPPER_RIGHT_CORNERPIECE_ACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_BOTTOM_FILLERS},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_VISUALIZATION_MINISCREEN},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_UPPER_LEFT_CORNERPIECE_INACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_PLAYLIST_TITLEBAR_INACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_TOP_FILLERS_INACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_UPPER_RIGHT_CORNERPIECE_INACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_LEFT_SIDE_FILLERS},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_RIGHT_SIDE_FILLERS_LEFT_BAR},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_RIGHT_SIDE_FILLERS_SCROLL_GROOVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_RIGHT_SIDE_FILLERS_RIGHT_BAR},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_CLOSE_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_WINDOWSHADE_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_WINDOWSHADE_LEFT_END},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_WINDOWSHADE_RIGHT_END_ACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_MAXIMIZE_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_SCROLL_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_SCROLL_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_WINDOWSHADE_MIDDLE_FILLERS},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_WINDOWSHADE_RIGHT_END_INACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_BOTTOM_LEFT_CONTROL_BAR},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_BOTTOM_RIGHT_CONTROL_BAR},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_PAGE_UP_BUTTON},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_PAGE_DOWN_BUTTON},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_ADD_BUTTON},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_REMOVE_BUTTON},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_SELECTION_BUTTON},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_MISCELLANEOUS_BUTTON},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_LIST_BUTTON},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_TIME_STATUS_BUTTON},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_RESIZE_CONTROL},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_PREVIOUS_CONTROL},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_PLAY_CONTROL},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_PAUSE_CONTROL},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_STOP_CONTROL},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_NEXT_CONTROL},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_OPEN_CONTROL},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_CURRENT_TIME_DISPLAY_MINUTES},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_CURRENT_TIME_DISPLAY_SECONDS},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_ADD_URL_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_ADD_URL_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_DECORATION_BAR_ADD},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_REMOVE_ALL_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_REMOVE_ALL_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_DECORATIVE_BAR_REMOVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_INVERT_SELECTION_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_INVERT_SELECTION_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_DECORATION_BAR_SELECTION},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_SORT_LIST_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_SORT_LIST_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_DECORATION_BAR_MISC},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_NEW_LIST_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_NEW_LIST_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_DECORATION_BAR_LIST},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_ADD_DIR_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_ADD_DIR_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_CROP_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_CROP_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_SELECT_NONE_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_SELECT_NONE_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_FILE_INFO_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_FILE_INFO_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_SAVE_LIST_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_SAVE_LIST_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_ADD_FILE_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_ADD_FILE_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_REMOVE_FILE_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_REMOVE_FILE_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_SELECT_ALL_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_SELECT_ALL_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_MISC_OPTIONS_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_MISC_OPTIONS_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_LOAD_LIST_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_LOAD_LIST_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_MISC_REMOVE_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=PLEDIT_MISC_REMOVE_BUTTON_PRESSED},

// from posbar.bmp
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=POSBAR_SONG_PROGRESS_BAR},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=POSBAR_SONG_SLIDER_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=POSBAR_SONG_SLIDER_PRESSED},

// from shufrep.bmp
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=SHUFREP_NO_REPEAT_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=SHUFREP_NO_SHUFFLE_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=SHUFREP_NO_REPEAT_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=SHUFREP_NO_SHUFFLE_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=SHUFREP_REPEAT_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=SHUFREP_SHUFFLE_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=SHUFREP_REPEAT_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=SHUFREP_SHUFFLE_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=SHUFREP_NO_EQUALIZER_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=SHUFREP_NO_PLAYLIST_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=SHUFREP_NO_EQUALIZER_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=SHUFREP_NO_PLAYLIST_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=SHUFREP_EQUALIZER_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=SHUFREP_PLAYLIST_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=SHUFREP_EQUALIZER_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=SHUFREP_PLAYLIST_PRESSED},

// from text.bmp
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_A},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_B},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_C},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_D},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_E},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_F},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_G},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_H},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_I},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_J},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_K},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_L},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_M},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_N},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_O},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_P},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_Q},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_R},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_S},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_T},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_U},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_V},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_W},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_X},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_Y},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_Z},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_QUOTATION_MARK},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_AT_SYMBOL},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_TIME_DISPLAY_BACKGROUND},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_TITLE_DISPLAY_SPACE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_0},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_1},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_2},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_3},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_4},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_5},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_6},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_7},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_8},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_9},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_ELLIPSIS},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_PERIOD},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_COLON},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_LEFT_PARENTHESIS},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_RIGHT_PARENTHESIS},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_DASH},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_APOSTROPHE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_EXCLAMATION_MARK},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_UNDERSCORE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_PLUS_SYMBOL},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_BACK_SLASH},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_SLASH},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_LEFT_BRACKET},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_RIGHT_BRACKET},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_CARROT},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_AMPERSAND},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_PERCENT},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_COMMA},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_EQUAL},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_DOLLAR},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_POUND},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_A_CIRCUMFLEX},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_O_UMLAUT},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_A_UMLAUT},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_QUESTION_MARK},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_ASTERISK},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TEXT_KBPS_DISPLAY_SPACE},

// from titlebar.bmp
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_MENU_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_MINIMIZE_BUTTON_UNPRESED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_EXIT_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_NORMAL_TITLEBAR_ACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_CLUTTERBAR_SHOWN},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_CLUTTERBAR_HIDDEN},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_MENU_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_MINIMIZE_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_EXIT_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_NORMAL_TITLEBAR_INACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_WINDOWSHADE_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_WINDOWSHADE_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_MAXIMIZE_BUTTON_UNPRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_MAXIMIZE_BUTTON_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_WINDOWSHADE_TITLEBAR_ACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_SONG_PROGRESS_BAR},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_SONG_PROGRESS_CONTROLS},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_WINDOWSHADE_TITLEBAR_INACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_CLUTTERBAR_O_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_CLUTTERBAR_A_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_CLUTTERBAR_I_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_CLUTTERBAR_D_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_CLUTTERBAR_V_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_ALTERNATIVE_TITLEBAR_ACTIVE},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=TITLEBAR_ALTERNATIVE_TITLEBAR_INACTIVE},

// from volume.bmp
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_000_001},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_003_005},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_007_009},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_011_013},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_015_017},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_019_021},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_023_025},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_027_029},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_031},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_033_035},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_037_039},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_041_043},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_045_047},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_049_050},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_052_054},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_056_058},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_060_062},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_064},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_066_068},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_070_072},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_074_076},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_078_080},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_082_084},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_086_088},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_090_092},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_094_096},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_098},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_100},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_SLIDER_PRESSED},
{.filename="avs.bmp",     .startx=    0,.starty=    0,.dimx=  0,.dimy=  0,.id=VOLUME_SLIDER_UNPRESSED}
		
};
