/*

Copyright 2022, dettus@dettus.net

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this 
   list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, 
   this list of conditions and the following disclaimer in the documentation 
   and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED 
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE 
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE 
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL 
DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR 
SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER 
CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, 
OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


*/
#include "elements.h"
// the information in this file was taken from the "Winamp 2.X skinnig tutorial" Version 1.5.0, copyright by Fyre

const tElements cElements[ELEMENTS_NUM]={
// from avs.bmp
	{.source=AVS_BMP,	.startx=   0,.starty=   0,.dimx=  0,.dimy=  0,.id=AVS_CLOSE_BUTTON_PRESSED},
	{.source=AVS_BMP,	.startx=  15,.starty=   0,.dimx= 50,.dimy= 15,.id=AVS_UPPER_LEFT_CORNER},
	{.source=AVS_BMP,	.startx=  66,.starty=  15,.dimx= 14,.dimy= 15,.id=AVS_TOP_FILLER},
	{.source=AVS_BMP,	.startx=  81,.starty=   0,.dimx= 16,.dimy= 15,.id=AVS_UPPER_RIGHT_CORNER},
	{.source=AVS_BMP,	.startx=   0,.starty=  16,.dimx=  7,.dimy=172,.id=AVS_LEFT_FILLER},
	{.source=AVS_BMP,	.startx=   8,.starty=  16,.dimx=  6,.dimy=172,.id=AVS_RIGHT_FILLER},
	{.source=AVS_BMP,	.startx=  15,.starty=  16,.dimx= 50,.dimy=  5,.id=AVS_LOWER_LEFT_CORNER},
	{.source=AVS_BMP,	.startx=  66,.starty=  16,.dimx= 14,.dimy=  5,.id=AVS_BOTTOM_FILLER},
	{.source=AVS_BMP,	.startx=  81,.starty=  16,.dimx= 16,.dimy=  5,.id=AVS_LOWER_RIGHT_CORNER},

// from balance.bmp
	{.source=BALANCE_BMP,.startx=    9,.starty=    0,.dimx= 38,.dimy= 13,.id=BALANCE_CENTERED},
	{.source=BALANCE_BMP,.startx=    9,.starty=   15,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER0},
	{.source=BALANCE_BMP,.startx=    9,.starty=   30,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER1},
	{.source=BALANCE_BMP,.startx=    9,.starty=   45,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER2},
	{.source=BALANCE_BMP,.startx=    9,.starty=   60,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER3},
	{.source=BALANCE_BMP,.startx=    9,.starty=   75,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER4},
	{.source=BALANCE_BMP,.startx=    9,.starty=   90,.dimx= 38,.dimy= 13,.id=BALANCE_24LEFTORRIGHT},
	{.source=BALANCE_BMP,.startx=    9,.starty=  105,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER5},
	{.source=BALANCE_BMP,.startx=    9,.starty=  120,.dimx= 38,.dimy= 13,.id=BALANCE_33LEFTORRIGHT},
	{.source=BALANCE_BMP,.startx=    9,.starty=  135,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER6},
	{.source=BALANCE_BMP,.startx=    9,.starty=  150,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER7},	
	{.source=BALANCE_BMP,.startx=    9,.starty=  165,.dimx= 38,.dimy= 13,.id=BALANCE_40LEFTORRIGHT},
	{.source=BALANCE_BMP,.startx=    9,.starty=  180,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER8},
	{.source=BALANCE_BMP,.startx=    9,.starty=  195,.dimx= 38,.dimy= 13,.id=BALANCE_49LEFTORRIGHT},
	{.source=BALANCE_BMP,.startx=    9,.starty=  210,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER9},
	{.source=BALANCE_BMP,.startx=    9,.starty=  225,.dimx= 38,.dimy= 13,.id=BALANCE_58LEFTORRIGHT},
	{.source=BALANCE_BMP,.startx=    9,.starty=  240,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER10},
	{.source=BALANCE_BMP,.startx=    9,.starty=  255,.dimx= 38,.dimy= 13,.id=BALANCE_66LEFTORRIGHT},
	{.source=BALANCE_BMP,.startx=    9,.starty=  270,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER11},
	{.source=BALANCE_BMP,.startx=    9,.starty=  285,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER12},
	{.source=BALANCE_BMP,.startx=    9,.starty=  300,.dimx= 38,.dimy= 13,.id=BALANCE_74LEFTORRIGHT},
	{.source=BALANCE_BMP,.startx=    9,.starty=  315,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER13},
	{.source=BALANCE_BMP,.startx=    9,.starty=  330,.dimx= 38,.dimy= 13,.id=BALANCE_82LEFTORRIGHT},
	{.source=BALANCE_BMP,.startx=    9,.starty=  345,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER14},
	{.source=BALANCE_BMP,.startx=    9,.starty=  360,.dimx= 38,.dimy= 13,.id=BALANCE_91LEFTORRIGHT},
	{.source=BALANCE_BMP,.startx=    9,.starty=  375,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER15},
	{.source=BALANCE_BMP,.startx=    9,.starty=  390,.dimx= 38,.dimy= 13,.id=BALANCE_FILLER16},
	{.source=BALANCE_BMP,.startx=    9,.starty=  405,.dimx= 38,.dimy= 13,.id=BALANCE_100LEFTORRIGHT},
	{.source=BALANCE_BMP,.startx=    0,.starty=  422,.dimx= 14,.dimy= 11,.id=BALANCE_SLIDER_PRESSED},
	{.source=BALANCE_BMP,.startx=   15,.starty=  422,.dimx= 14,.dimy= 11,.id=BALANCE_SLIDER_UNPRESSED},

// from cbuttons.bmp
	{.source=CBUTTONS_BMP,.startx=    0,.starty=    0,.dimx= 23,.dimy= 18,.id=CBUTTONS_PREV_BUTTON_UNPRESSED},
	{.source=CBUTTONS_BMP,.startx=   23,.starty=    0,.dimx= 23,.dimy= 18,.id=CBUTTONS_PLAY_BUTTON_UNPRESSED},
	{.source=CBUTTONS_BMP,.startx=   46,.starty=    0,.dimx= 23,.dimy= 18,.id=CBUTTONS_PAUSE_BUTTON_UNPRESSED},
	{.source=CBUTTONS_BMP,.startx=   69,.starty=    0,.dimx= 23,.dimy= 18,.id=CBUTTONS_STOP_BUTTON_UNPRESSED},
	{.source=CBUTTONS_BMP,.startx=   92,.starty=    0,.dimx= 22,.dimy= 18,.id=CBUTTONS_NEXT_BUTTON_UNPRESSED},
	{.source=CBUTTONS_BMP,.startx=  114,.starty=    0,.dimx= 22,.dimy= 16,.id=CBUTTONS_OPEN_BUTTON_UNPRESSED},
	{.source=CBUTTONS_BMP,.startx=    0,.starty=   18,.dimx= 23,.dimy= 18,.id=CBUTTONS_PREV_BUTTON_PRESSED},
	{.source=CBUTTONS_BMP,.startx=   23,.starty=   18,.dimx= 23,.dimy= 18,.id=CBUTTONS_PLAY_BUTTON_PRESSED},
	{.source=CBUTTONS_BMP,.startx=   46,.starty=   18,.dimx= 23,.dimy= 18,.id=CBUTTONS_PAUSE_BUTTON_PRESSED},
	{.source=CBUTTONS_BMP,.startx=   69,.starty=   18,.dimx= 23,.dimy= 18,.id=CBUTTONS_STOP_BUTTON_PRESSED},
	{.source=CBUTTONS_BMP,.startx=   92,.starty=   18,.dimx= 22,.dimy= 18,.id=CBUTTONS_NEXT_BUTTON_PRESSED},
	{.source=CBUTTONS_BMP,.startx=  114,.starty=   18,.dimx= 22,.dimy= 16,.id=CBUTTONS_OPEN_BUTTON_PRESSED},

// from eq_ex.bmp	
	{.source=EQ_EX_BMP,   .startx=    0,.starty=    0,.dimx=275,.dimy= 14,.id=EQEX_EQUALIZER_WINDOWSHADE_ACTIVE},
	{.source=EQ_EX_BMP,   .startx=   61,.starty=    4,.dimx= 97,.dimy=  7,.id=EQEX_VOLUMECONTROL_ACTIVE},
	{.source=EQ_EX_BMP,   .startx=  164,.starty=    4,.dimx= 42,.dimy=  7,.id=EQEX_BALANCECONTROL_ACTIVE},
	{.source=EQ_EX_BMP,   .startx=    0,.starty=   15,.dimx=275,.dimy= 14,.id=EQEX_EQUALIZER_WINDOWSHADE_INACTIVE},
	{.source=EQ_EX_BMP,   .startx=   61,.starty=   19,.dimx= 97,.dimy=  7,.id=EQEX_VOLUMECONTROL_INACTIVE},
	{.source=EQ_EX_BMP,   .startx=  164,.starty=   19,.dimx= 42,.dimy=  7,.id=EQEX_BALANCECONTROL_INACTIVE},
	{.source=EQ_EX_BMP,   .startx=    1,.starty=   30,.dimx=  3,.dimy=  7,.id=EQEX_VOLUMESLIDER_LOW},
	{.source=EQ_EX_BMP,   .startx=    4,.starty=   30,.dimx=  3,.dimy=  7,.id=EQEX_VOLUMESLIDER_MEDIUM},
	{.source=EQ_EX_BMP,   .startx=    7,.starty=   30,.dimx=  3,.dimy=  7,.id=EQEX_VOLUMESLIDER_HIGH},
	{.source=EQ_EX_BMP,   .startx=   11,.starty=   30,.dimx=  3,.dimy=  7,.id=EQEX_BALANCESLIDER_LEFT},
	{.source=EQ_EX_BMP,   .startx=   14,.starty=   30,.dimx=  3,.dimy=  7,.id=EQEX_BALANCESLIDER_MIDDLE},
	{.source=EQ_EX_BMP,   .startx=   17,.starty=   30,.dimx=  3,.dimy=  7,.id=EQEX_BALANCESLIDER_RIGHT},
	{.source=EQ_EX_BMP,   .startx=    1,.starty=   38,.dimx=  9,.dimy=  9,.id=EQEX_WINDOWSHADE_BUTTON_PRESSED},
	{.source=EQ_EX_BMP,   .startx=   11,.starty=   38,.dimx=  9,.dimy=  9,.id=EQEX_CLOSEBUTTON_UNPRESSED},
	{.source=EQ_EX_BMP,   .startx=    1,.starty=   47,.dimx=  9,.dimy=  9,.id=EQEX_MAXIMIZEBUTTON_PRESSED},
	{.source=EQ_EX_BMP,   .startx=   11,.starty=   47,.dimx=  9,.dimy=  9,.id=EQEX_CLOSEBUTTON_PRESSED},

// from eqmain.bmp
	{.source=EQMAIN_BMP,  .startx=    0,.starty=    0,.dimx=275,.dimy= 14,.id=EQMAIN_EQUALIZER_TITLEBAR},
	{.source=EQMAIN_BMP,  .startx=    0,.starty=   14,.dimx=275,.dimy=102,.id=EQMAIN_EQUALIZER_MAIN_DISPLAY},
	{.source=EQMAIN_BMP,  .startx=   86,.starty=   16,.dimx=113,.dimy= 20,.id=EQMAIN_EQUALIZER_MINIDISPLAY},
	{.source=EQMAIN_BMP,  .startx=   14,.starty=   18,.dimx= 25,.dimy= 12,.id=EQMAIN_EQUALIZER_ON},
	{.source=EQMAIN_BMP,  .startx=   39,.starty=   18,.dimx= 33,.dimy= 12,.id=EQMAIN_AUTOMATIC_EQUALIZATION},
	{.source=EQMAIN_BMP,  .startx=  217,.starty=   18,.dimx= 44,.dimy= 12,.id=EQMAIN_OPEN_PRESET_MENU},
	{.source=EQMAIN_BMP,  .startx=   42,.starty=   33,.dimx= 26,.dimy= 10,.id=EQMAIN_20DB_RESET},
	{.source=EQMAIN_BMP,  .startx=   21,.starty=   38,.dimx= 14,.dimy= 63,.id=EQMAIN_PREAMP_BAR},
	{.source=EQMAIN_BMP,  .startx=   78,.starty=   38,.dimx= 14,.dimy= 63,.id=EQMAIN_60HZ_BAR},
	{.source=EQMAIN_BMP,  .startx=   96,.starty=   38,.dimx= 14,.dimy= 63,.id=EQMAIN_170HZ_BAR},
	{.source=EQMAIN_BMP,  .startx=  114,.starty=   38,.dimx= 14,.dimy= 63,.id=EQMAIN_310HZ_BAR},
	{.source=EQMAIN_BMP,  .startx=  132,.starty=   38,.dimx= 14,.dimy= 63,.id=EQMAIN_600HZ_BAR},
	{.source=EQMAIN_BMP,  .startx=  150,.starty=   38,.dimx= 14,.dimy= 63,.id=EQMAIN_1KHZ_BAR},
	{.source=EQMAIN_BMP,  .startx=  168,.starty=   38,.dimx= 14,.dimy= 63,.id=EQMAIN_3KHZ_BAR},
	{.source=EQMAIN_BMP,  .startx=  186,.starty=   38,.dimx= 14,.dimy= 63,.id=EQMAIN_6KHZ_BAR},
	{.source=EQMAIN_BMP,  .startx=  204,.starty=   38,.dimx= 14,.dimy= 63,.id=EQMAIN_12KHZ_BAR},
	{.source=EQMAIN_BMP,  .startx=  222,.starty=   38,.dimx= 14,.dimy= 63,.id=EQMAIN_14KHZ_BAR},
	{.source=EQMAIN_BMP,  .startx=  240,.starty=   38,.dimx= 14,.dimy= 63,.id=EQMAIN_16KHZ_BAR},
	{.source=EQMAIN_BMP,  .startx=   42,.starty=   65,.dimx= 26,.dimy= 10,.id=EQMAIN_0DB_RESET},
	{.source=EQMAIN_BMP,  .startx=   42,.starty=   92,.dimx= 26,.dimy= 10,.id=EQMAIN_M20DB_RESET},
	{.source=EQMAIN_BMP,  .startx=    0,.starty=  116,.dimx=  9,.dimy=  9,.id=EQMAIN_CLOSE_BUTTON_UNPRESSED},
	{.source=EQMAIN_BMP,  .startx=   10,.starty=  119,.dimx= 25,.dimy= 12,.id=EQMAIN_EQUALIZER_OFF_UNPRESSED},
	{.source=EQMAIN_BMP,  .startx=   35,.starty=  119,.dimx= 33,.dimy= 12,.id=EQMAIN_AUTO_OFF_UNPRESSED},
	{.source=EQMAIN_BMP,  .startx=   69,.starty=  119,.dimx= 25,.dimy= 12,.id=EQMAIN_EQUALIZER_ON_UNPRESSED},
	{.source=EQMAIN_BMP,  .startx=   94,.starty=  119,.dimx= 33,.dimy= 12,.id=EQMAIN_AUTO_ON_UNPRESSED},
	{.source=EQMAIN_BMP,  .startx=  128,.starty=  119,.dimx= 25,.dimy= 12,.id=EQMAIN_EQUALIZER_OFF_PRESSED},
	{.source=EQMAIN_BMP,  .startx=  153,.starty=  119,.dimx= 33,.dimy= 12,.id=EQMAIN_AUTO_OFF_PRESSED},
	{.source=EQMAIN_BMP,  .startx=  187,.starty=  119,.dimx= 25,.dimy= 12,.id=EQMAIN_EQUALIZER_ON_PRESSED},
	{.source=EQMAIN_BMP,  .startx=  212,.starty=  119,.dimx= 33,.dimy= 12,.id=EQMAIN_AUTO_ON_PRESSED},
	{.source=EQMAIN_BMP,  .startx=    0,.starty=  125,.dimx=  9,.dimy=  9,.id=EQMAIN_CLOSE_BUTTON_PRESSED},
	{.source=EQMAIN_BMP,  .startx=    0,.starty=  134,.dimx=275,.dimy= 14,.id=EQMAIN_EQUALIZER_TITLEBAR_ACTIVE},
	{.source=EQMAIN_BMP,  .startx=    0,.starty=  149,.dimx=275,.dimy= 14,.id=EQMAIN_EQUALIZER_TITLEBAR_INACTIVE},
	{.source=EQMAIN_BMP,  .startx=    0,.starty=  164,.dimx= 11,.dimy= 11,.id=EQMAIN_EQUALIZER_SLIDER_UNPRESSED},
	{.source=EQMAIN_BMP,  .startx=   13,.starty=  164,.dimx= 14,.dimy= 63,.id=EQMAIN_M2000DB_BAR},
	{.source=EQMAIN_BMP,  .startx=   28,.starty=  164,.dimx= 14,.dimy= 63,.id=EQMAIN_M1875DB_BAR},
	{.source=EQMAIN_BMP,  .startx=   43,.starty=  164,.dimx= 14,.dimy= 63,.id=EQMAIN_M1714DB_BAR},
	{.source=EQMAIN_BMP,  .startx=   58,.starty=  164,.dimx= 14,.dimy= 63,.id=EQMAIN_M1571DB_BAR},
	{.source=EQMAIN_BMP,  .startx=   73,.starty=  164,.dimx= 14,.dimy= 63,.id=EQMAIN_M1429DB_BAR},
	{.source=EQMAIN_BMP,  .startx=   88,.starty=  164,.dimx= 14,.dimy= 63,.id=EQMAIN_M1286DB_BAR},
	{.source=EQMAIN_BMP,  .startx=  103,.starty=  164,.dimx= 14,.dimy= 63,.id=EQMAIN_M1143DB_BAR},
	{.source=EQMAIN_BMP,  .startx=  118,.starty=  164,.dimx= 14,.dimy= 63,.id=EQMAIN_M1000DB_BAR},
	{.source=EQMAIN_BMP,  .startx=  133,.starty=  164,.dimx= 14,.dimy= 63,.id=EQMAIN_M0857DB_BAR},
	{.source=EQMAIN_BMP,  .startx=  148,.starty=  164,.dimx= 14,.dimy= 63,.id=EQMAIN_M0714DB_BAR},
	{.source=EQMAIN_BMP,  .startx=  163,.starty=  164,.dimx= 14,.dimy= 63,.id=EQMAIN_M0571DB_BAR},
	{.source=EQMAIN_BMP,  .startx=  178,.starty=  164,.dimx= 14,.dimy= 63,.id=EQMAIN_M0428DB_BAR},
	{.source=EQMAIN_BMP,  .startx=  193,.starty=  164,.dimx= 14,.dimy= 63,.id=EQMAIN_M0285DB_BAR},
	{.source=EQMAIN_BMP,  .startx=  208,.starty=  164,.dimx= 14,.dimy= 63,.id=EQMAIN_M0142DB_BAR},
	{.source=EQMAIN_BMP,  .startx=  224,.starty=  164,.dimx= 44,.dimy= 12,.id=EQMAIN_PRESET_BUTTON_UNPRESSED},
	{.source=EQMAIN_BMP,  .startx=    0,.starty=  176,.dimx= 11,.dimy= 11,.id=EQMAIN_EQUALIZER_SLIDER_PRESSED},
	{.source=EQMAIN_BMP,  .startx=  224,.starty=  176,.dimx= 44,.dimy= 12,.id=EQMAIN_PRESET_BUTTON_PRESSED},
	{.source=EQMAIN_BMP,  .startx=   13,.starty=  229,.dimx= 14,.dimy= 63,.id=EQMAIN_P0142DB_BAR},
	{.source=EQMAIN_BMP,  .startx=   28,.starty=  229,.dimx= 14,.dimy= 63,.id=EQMAIN_P0285DB_BAR},
	{.source=EQMAIN_BMP,  .startx=   43,.starty=  229,.dimx= 14,.dimy= 63,.id=EQMAIN_P0428DB_BAR},
	{.source=EQMAIN_BMP,  .startx=   58,.starty=  229,.dimx= 14,.dimy= 63,.id=EQMAIN_P0571DB_BAR},
	{.source=EQMAIN_BMP,  .startx=   73,.starty=  229,.dimx= 14,.dimy= 63,.id=EQMAIN_P0714DB_BAR},
	{.source=EQMAIN_BMP,  .startx=   88,.starty=  229,.dimx= 14,.dimy= 63,.id=EQMAIN_P0857DB_BAR},
	{.source=EQMAIN_BMP,  .startx=  103,.starty=  229,.dimx= 14,.dimy= 63,.id=EQMAIN_P1000DB_BAR},
	{.source=EQMAIN_BMP,  .startx=  118,.starty=  229,.dimx= 14,.dimy= 63,.id=EQMAIN_P1143DB_BAR},
	{.source=EQMAIN_BMP,  .startx=  133,.starty=  229,.dimx= 14,.dimy= 63,.id=EQMAIN_P1286DB_BAR},
	{.source=EQMAIN_BMP,  .startx=  148,.starty=  229,.dimx= 14,.dimy= 63,.id=EQMAIN_P1429DB_BAR},
	{.source=EQMAIN_BMP,  .startx=  153,.starty=  229,.dimx= 14,.dimy= 63,.id=EQMAIN_P1571DB_BAR},
	{.source=EQMAIN_BMP,  .startx=  178,.starty=  229,.dimx= 14,.dimy= 63,.id=EQMAIN_P1714DB_BAR},
	{.source=EQMAIN_BMP,  .startx=  193,.starty=  229,.dimx= 14,.dimy= 63,.id=EQMAIN_P1857DB_BAR},
	{.source=EQMAIN_BMP,  .startx=  208,.starty=  229,.dimx= 14,.dimy= 63,.id=EQMAIN_P2000DB_BAR},
	{.source=EQMAIN_BMP,  .startx=    0,.starty=  293,.dimx=113,.dimy= 20,.id=EQMAIN_ACTUAL_EQUALIZER_MINIDISPLAY},
	{.source=EQMAIN_BMP,  .startx=  115,.starty=  294,.dimx=  1,.dimy= 19,.id=EQMAIN_SPLINE_LINE},
	{.source=EQMAIN_BMP,  .startx=    0,.starty=  314,.dimx=113,.dimy=  1,.id=EQMAIN_PREAMP_LINE},

// from main.bmp
	{.source=MAIN_BMP,    .startx=    0,.starty=   14,.dimx=275,.dimy=102,.id=MAIN_MAIN_DISPLAY},
	{.source=MAIN_BMP,    .startx=  111,.starty=   27,.dimx=111,.dimy= 27,.id=MAIN_SONG_INFO_DISPLAY},
	{.source=MAIN_BMP,    .startx=  111,.starty=   43,.dimx= 15,.dimy=  6,.id=MAIN_KBPS_DISPLAY},
	{.source=MAIN_BMP,    .startx=  156,.starty=   43,.dimx= 10,.dimy=  6,.id=MAIN_KHZ_DISPLAY},
	{.source=MAIN_BMP,    .startx=   24,.starty=   44,.dimx= 76,.dimy= 15,.id=MAIN_VISUALIZATION_WINDOW},
	{.source=MAIN_BMP,    .startx=  253,.starty=   91,.dimx= 13,.dimy= 15,.id=MAIN_INFO},

// from mb (minibrowser)
	{.source=MB_BMP,      .startx=    0,.starty=    0,.dimx= 25,.dimy= 20,.id=MB_UPPER_LEFT_CORNERPIECE_ACTIVE},
	{.source=MB_BMP,      .startx=   26,.starty=    0,.dimx=100,.dimy= 20,.id=MB_TITLEBAR_ACTIVE},
	{.source=MB_BMP,      .startx=  127,.starty=    0,.dimx= 25,.dimy= 20,.id=MB_TOP_FILLERS_ACTIVE},
	{.source=MB_BMP,      .startx=  153,.starty=    0,.dimx= 25,.dimy= 20,.id=MB_UPPER_RIGHT_CORNERPIECE_ACTIVE},
	{.source=MB_BMP,      .startx=    0,.starty=   21,.dimx= 25,.dimy= 20,.id=MB_UPPER_LEFT_CORNERPIECE_INACTIVE},
	{.source=MB_BMP,      .startx=   26,.starty=   21,.dimx=100,.dimy= 20,.id=MB_TITLEBAR_INACTIVE},
	{.source=MB_BMP,      .startx=  127,.starty=   21,.dimx= 25,.dimy= 20,.id=MB_TOPFILLERS_INACTIVE},
	{.source=MB_BMP,      .startx=  153,.starty=   21,.dimx= 25,.dimy= 20,.id=MB_UPPER_RIGHT_CORNERPIECE_INACTIVE},
	{.source=MB_BMP,      .startx=    0,.starty=   42,.dimx=125,.dimy= 38,.id=MB_BOTTOM_LEFT_CONTROLBAR},
	{.source=MB_BMP,      .startx=  127,.starty=   42,.dimx= 11,.dimy= 29,.id=MB_LEFT_SIDE_FILLERS},
	{.source=MB_BMP,      .startx=  139,.starty=   42,.dimx=  8,.dimy= 29,.id=MB_RIGHT_SIDE_FILLERS},
	{.source=MB_BMP,      .startx=  148,.starty=   42,.dimx=  9,.dimy=  9,.id=MB_CLOSE_BUTTON_PRESSED},
	{.source=MB_BMP,      .startx=  158,.starty=   42,.dimx= 15,.dimy= 18,.id=MB_BACK_BUTTON_PRESSED},
	{.source=MB_BMP,      .startx=  173,.starty=   42,.dimx= 15,.dimy= 18,.id=MB_FORWARD_BUTTON_PRESSED},
	{.source=MB_BMP,      .startx=  188,.starty=   42,.dimx= 15,.dimy= 18,.id=MB_STOP_BUTTON_PRESSED},
	{.source=MB_BMP,      .startx=  203,.starty=   42,.dimx= 15,.dimy= 18,.id=MB_RELOAD_BUTTON_PRESSED},
	{.source=MB_BMP,      .startx=  218,.starty=   42,.dimx= 15,.dimy= 18,.id=MB_OPTIONS_BUTTON_PRESSED},
	{.source=MB_BMP,      .startx=    9,.starty=   51,.dimx= 15,.dimy= 18,.id=MB_BACK_BUTTON_UNPRESSED},
	{.source=MB_BMP,      .startx=   24,.starty=   51,.dimx= 15,.dimy= 18,.id=MB_FORWARD_BUTTON_UNPRESSED},
	{.source=MB_BMP,      .startx=   39,.starty=   51,.dimx= 15,.dimy= 18,.id=MB_STOP_BUTTON_UNPRESSED},
	{.source=MB_BMP,      .startx=   54,.starty=   51,.dimx= 15,.dimy= 18,.id=MB_RELOAD_BUTTON_UNPRESSED},
	{.source=MB_BMP,      .startx=   69,.starty=   53,.dimx= 15,.dimy= 18,.id=MB_OPTIONS_BUTTON_UNPRESSED},
	{.source=MB_BMP,      .startx=   92,.starty=   81,.dimx= 33,.dimy= 13,.id=MB_URL_DISPLAY_BAR_LEFT_END},
	{.source=MB_BMP,      .startx=    0,.starty=   81,.dimx=125,.dimy= 38,.id=MB_BOTTOM_RIGHT_CONTROL_BAR},
	{.source=MB_BMP,      .startx=  127,.starty=   92,.dimx= 25,.dimy= 38,.id=MB_BOTTOM_FILLER},
	{.source=MB_BMP,      .startx=    0,.starty=   92,.dimx=100,.dimy= 13,.id=MB_URL_DISPLAY_BAR_RIGHT_END},
	{.source=MB_BMP,      .startx=  127,.starty=   92,.dimx= 68,.dimy= 13,.id=MB_DISPLAY_BAR_FILLER},
	{.source=MB_BMP,      .startx=  107,.starty=  102,.dimx= 18,.dimy= 17,.id=MB_RESIZE_CONTROL},

// from monoster.bmp
	{.source=MONOSTER_BMP,.startx=    0,.starty=    0,.dimx= 29,.dimy= 12,.id=MONOSTER_STEREO_ACTIVE},
	{.source=MONOSTER_BMP,.startx=   29,.starty=    0,.dimx= 27,.dimy= 12,.id=MONOSTER_MONO_ACTIVE},
	{.source=MONOSTER_BMP,.startx=    0,.starty=   12,.dimx= 29,.dimy= 12,.id=MONOSTER_STEREO_INACTIVE},
	{.source=MONOSTER_BMP,.startx=   29,.starty=   12,.dimx= 27,.dimy= 12,.id=MONOSTER_MONO_INACTIVE},

// from numbers.bmp
	{.source=NUMBERS_BMP, .startx=    0,.starty=    0,.dimx=  9,.dimy= 13,.id=NUMBERS_0},
	{.source=NUMBERS_BMP, .startx=    9,.starty=    0,.dimx=  9,.dimy= 13,.id=NUMBERS_1},
	{.source=NUMBERS_BMP, .startx=   18,.starty=    0,.dimx=  9,.dimy= 13,.id=NUMBERS_2},
	{.source=NUMBERS_BMP, .startx=   27,.starty=    0,.dimx=  9,.dimy= 13,.id=NUMBERS_3},
	{.source=NUMBERS_BMP, .startx=   36,.starty=    0,.dimx=  9,.dimy= 13,.id=NUMBERS_4},
	{.source=NUMBERS_BMP, .startx=   45,.starty=    0,.dimx=  9,.dimy= 13,.id=NUMBERS_5},
	{.source=NUMBERS_BMP, .startx=   54,.starty=    0,.dimx=  9,.dimy= 13,.id=NUMBERS_6},
	{.source=NUMBERS_BMP, .startx=   63,.starty=    0,.dimx=  9,.dimy= 13,.id=NUMBERS_7},
	{.source=NUMBERS_BMP, .startx=   72,.starty=    0,.dimx=  9,.dimy= 13,.id=NUMBERS_8},
	{.source=NUMBERS_BMP, .startx=   81,.starty=    0,.dimx=  9,.dimy= 13,.id=NUMBERS_9},
	{.source=NUMBERS_BMP, .startx=   90,.starty=    0,.dimx=  9,.dimy= 13,.id=NUMBERS_BLANK},

// from playpause.bmp
	{.source=PLAYPAUS_BMP,.startx=    1,.starty=    0,.dimx=  8,.dimy=  9,.id=PLAYPAUSE_PLAY_INDICATOR},
	{.source=PLAYPAUS_BMP,.startx=    9,.starty=    0,.dimx=  9,.dimy=  9,.id=PLAYPAUSE_PAUSE_INDICATOR},
	{.source=PLAYPAUS_BMP,.startx=   18,.starty=    0,.dimx=  9,.dimy=  9,.id=PLAYPAUSE_STOP_INDICATOR},
	{.source=PLAYPAUS_BMP,.startx=   27,.starty=    0,.dimx=  2,.dimy=  9,.id=PLAYPAUSE_FILLER},
	{.source=PLAYPAUS_BMP,.startx=   36,.starty=    0,.dimx=  3,.dimy=  9,.id=PLAYPAUSE_START_OF_SONG_INDICATOR},
	{.source=PLAYPAUS_BMP,.startx=   39,.starty=    0,.dimx=  3,.dimy=  9,.id=PLAYPAUSE_END_OF_SONG_INDICATOR},

// from pledit.bmp
	{.source=PLEDIT_BMP,  .startx=    0,.starty=    0,.dimx= 25,.dimy= 20,.id=PLEDIT_UPPER_LEFT_CORNERPIECE_ACTIVE},
	{.source=PLEDIT_BMP,  .startx=   26,.starty=    0,.dimx=100,.dimy= 20,.id=PLEDIT_PLAYLIST_TITLEBAR_ACTIVE},
	{.source=PLEDIT_BMP,  .startx=  127,.starty=    0,.dimx= 25,.dimy= 20,.id=PLEDIT_TOP_FILLERS_ACTIVE},
	{.source=PLEDIT_BMP,  .startx=  153,.starty=    0,.dimx= 25,.dimy= 20,.id=PLEDIT_UPPER_RIGHT_CORNERPIECE_ACTIVE},
	{.source=PLEDIT_BMP,  .startx=  179,.starty=    0,.dimx= 25,.dimy= 20,.id=PLEDIT_BOTTOM_FILLERS},
	{.source=PLEDIT_BMP,  .startx=  205,.starty=    0,.dimx= 75,.dimy= 20,.id=PLEDIT_VISUALIZATION_MINISCREEN},
	{.source=PLEDIT_BMP,  .startx=    0,.starty=   21,.dimx= 25,.dimy= 20,.id=PLEDIT_UPPER_LEFT_CORNERPIECE_INACTIVE},
	{.source=PLEDIT_BMP,  .startx=   26,.starty=   21,.dimx=100,.dimy= 20,.id=PLEDIT_PLAYLIST_TITLEBAR_INACTIVE},
	{.source=PLEDIT_BMP,  .startx=  127,.starty=   21,.dimx= 25,.dimy= 20,.id=PLEDIT_TOP_FILLERS_INACTIVE},
	{.source=PLEDIT_BMP,  .startx=  153,.starty=   21,.dimx= 25,.dimy= 20,.id=PLEDIT_UPPER_RIGHT_CORNERPIECE_INACTIVE},
	{.source=PLEDIT_BMP,  .startx=    0,.starty=   42,.dimx= 12,.dimy= 29,.id=PLEDIT_LEFT_SIDE_FILLERS},
	{.source=PLEDIT_BMP,  .startx=   31,.starty=   42,.dimx=  5,.dimy= 29,.id=PLEDIT_RIGHT_SIDE_FILLERS_LEFT_BAR},
	{.source=PLEDIT_BMP,  .startx=   36,.starty=   42,.dimx=  8,.dimy= 29,.id=PLEDIT_RIGHT_SIDE_FILLERS_SCROLL_GROOVE},
	{.source=PLEDIT_BMP,  .startx=   44,.starty=   42,.dimx=  7,.dimy= 29,.id=PLEDIT_RIGHT_SIDE_FILLERS_RIGHT_BAR},
	{.source=PLEDIT_BMP,  .startx=   52,.starty=   42,.dimx=  9,.dimy=  9,.id=PLEDIT_CLOSE_BUTTON_PRESSED},
	{.source=PLEDIT_BMP,  .startx=   62,.starty=   42,.dimx=  9,.dimy=  9,.id=PLEDIT_WINDOWSHADE_BUTTON_PRESSED},
	{.source=PLEDIT_BMP,  .startx=   72,.starty=   42,.dimx= 25,.dimy= 14,.id=PLEDIT_WINDOWSHADE_LEFT_END},
	{.source=PLEDIT_BMP,  .startx=   99,.starty=   42,.dimx= 50,.dimy= 14,.id=PLEDIT_WINDOWSHADE_RIGHT_END_ACTIVE},
	{.source=PLEDIT_BMP,  .startx=  150,.starty=   42,.dimx=  9,.dimy=  9,.id=PLEDIT_MAXIMIZE_BUTTON_PRESSED},
	{.source=PLEDIT_BMP,  .startx=   52,.starty=   53,.dimx=  8,.dimy= 18,.id=PLEDIT_SCROLL_BUTTON_UNPRESSED},
	{.source=PLEDIT_BMP,  .startx=   62,.starty=   53,.dimx=  8,.dimy= 18,.id=PLEDIT_SCROLL_BUTTON_PRESSED},
	{.source=PLEDIT_BMP,  .startx=   72,.starty=   57,.dimx= 25,.dimy= 14,.id=PLEDIT_WINDOWSHADE_MIDDLE_FILLERS},
	{.source=PLEDIT_BMP,  .startx=   99,.starty=   57,.dimx= 50,.dimy= 14,.id=PLEDIT_WINDOWSHADE_RIGHT_END_INACTIVE},
	{.source=PLEDIT_BMP,  .startx=    0,.starty=   72,.dimx=125,.dimy= 38,.id=PLEDIT_BOTTOM_LEFT_CONTROL_BAR},
	{.source=PLEDIT_BMP,  .startx=  126,.starty=   72,.dimx=150,.dimy= 38,.id=PLEDIT_BOTTOM_RIGHT_CONTROL_BAR},
	{.source=PLEDIT_BMP,  .startx=  261,.starty=   74,.dimx=  9,.dimy=  5,.id=PLEDIT_PAGE_UP_BUTTON},
	{.source=PLEDIT_BMP,  .startx=  261,.starty=   79,.dimx=  9,.dimy=  5,.id=PLEDIT_PAGE_DOWN_BUTTON},
	{.source=PLEDIT_BMP,  .startx=   14,.starty=   80,.dimx= 22,.dimy= 18,.id=PLEDIT_ADD_BUTTON},
	{.source=PLEDIT_BMP,  .startx=   43,.starty=   80,.dimx= 22,.dimy= 18,.id=PLEDIT_REMOVE_BUTTON},
	{.source=PLEDIT_BMP,  .startx=   72,.starty=   80,.dimx= 22,.dimy= 18,.id=PLEDIT_SELECTION_BUTTON},
	{.source=PLEDIT_BMP,  .startx=  101,.starty=   80,.dimx= 22,.dimy= 18,.id=PLEDIT_MISCELLANEOUS_BUTTON},
	{.source=PLEDIT_BMP,  .startx=  232,.starty=   80,.dimx= 22,.dimy= 18,.id=PLEDIT_LIST_BUTTON},
	{.source=PLEDIT_BMP,  .startx=  133,.starty=   82,.dimx= 90,.dimy=  6,.id=PLEDIT_TIME_STATUS_BUTTON},
	{.source=PLEDIT_BMP,  .startx=  257,.starty=   89,.dimx= 19,.dimy= 21,.id=PLEDIT_RESIZE_CONTROL},
	{.source=PLEDIT_BMP,  .startx=  132,.starty=   94,.dimx=  7,.dimy=  8,.id=PLEDIT_PREVIOUS_CONTROL},
	{.source=PLEDIT_BMP,  .startx=  140,.starty=   94,.dimx=  8,.dimy=  8,.id=PLEDIT_PLAY_CONTROL},
	{.source=PLEDIT_BMP,  .startx=  149,.starty=   94,.dimx=  9,.dimy=  8,.id=PLEDIT_PAUSE_CONTROL},
	{.source=PLEDIT_BMP,  .startx=  159,.starty=   94,.dimx=  9,.dimy=  8,.id=PLEDIT_STOP_CONTROL},
	{.source=PLEDIT_BMP,  .startx=  169,.starty=   94,.dimx=  7,.dimy=  8,.id=PLEDIT_NEXT_CONTROL},
	{.source=PLEDIT_BMP,  .startx=  177,.starty=   94,.dimx=  9,.dimy=  8,.id=PLEDIT_OPEN_CONTROL},
	{.source=PLEDIT_BMP,  .startx=  190,.starty=   95,.dimx= 19,.dimy=  6,.id=PLEDIT_CURRENT_TIME_DISPLAY_MINUTES},
	{.source=PLEDIT_BMP,  .startx=  212,.starty=   95,.dimx= 10,.dimy=  6,.id=PLEDIT_CURRENT_TIME_DISPLAY_SECONDS},
	{.source=PLEDIT_BMP,  .startx=    0,.starty=  111,.dimx= 22,.dimy= 18,.id=PLEDIT_ADD_URL_BUTTON_UNPRESSED},
	{.source=PLEDIT_BMP,  .startx=   23,.starty=  111,.dimx= 22,.dimy= 18,.id=PLEDIT_ADD_URL_BUTTON_PRESSED},
	{.source=PLEDIT_BMP,  .startx=   48,.starty=  111,.dimx=  3,.dimy= 54,.id=PLEDIT_DECORATION_BAR_ADD},
	{.source=PLEDIT_BMP,  .startx=   54,.starty=  111,.dimx= 22,.dimy= 18,.id=PLEDIT_REMOVE_ALL_BUTTON_UNPRESSED},
	{.source=PLEDIT_BMP,  .startx=   77,.starty=  111,.dimx= 22,.dimy= 18,.id=PLEDIT_REMOVE_ALL_BUTTON_PRESSED},
	{.source=PLEDIT_BMP,  .startx=  100,.starty=  111,.dimx=  3,.dimy= 72,.id=PLEDIT_DECORATIVE_BAR_REMOVE},
	{.source=PLEDIT_BMP,  .startx=  104,.starty=  111,.dimx= 22,.dimy= 18,.id=PLEDIT_INVERT_SELECTION_BUTTON_UNPRESSED},
	{.source=PLEDIT_BMP,  .startx=  127,.starty=  111,.dimx= 22,.dimy= 18,.id=PLEDIT_INVERT_SELECTION_BUTTON_PRESSED},
	{.source=PLEDIT_BMP,  .startx=  150,.starty=  111,.dimx=  3,.dimy= 54,.id=PLEDIT_DECORATION_BAR_SELECTION},
	{.source=PLEDIT_BMP,  .startx=  154,.starty=  111,.dimx= 22,.dimy= 18,.id=PLEDIT_SORT_LIST_BUTTON_UNPRESSED},
	{.source=PLEDIT_BMP,  .startx=  177,.starty=  111,.dimx= 22,.dimy= 18,.id=PLEDIT_SORT_LIST_BUTTON_PRESSED},
	{.source=PLEDIT_BMP,  .startx=  200,.starty=  111,.dimx=  3,.dimy= 54,.id=PLEDIT_DECORATION_BAR_MISC},
	{.source=PLEDIT_BMP,  .startx=  204,.starty=  111,.dimx= 22,.dimy= 18,.id=PLEDIT_NEW_LIST_BUTTON_UNPRESSED},
	{.source=PLEDIT_BMP,  .startx=  227,.starty=  111,.dimx= 22,.dimy= 18,.id=PLEDIT_NEW_LIST_BUTTON_PRESSED},
	{.source=PLEDIT_BMP,  .startx=  250,.starty=  111,.dimx=  3,.dimy= 54,.id=PLEDIT_DECORATION_BAR_LIST},
	{.source=PLEDIT_BMP,  .startx=    0,.starty=  130,.dimx= 22,.dimy= 18,.id=PLEDIT_ADD_DIR_BUTTON_UNPRESSED},
	{.source=PLEDIT_BMP,  .startx=   23,.starty=  130,.dimx= 22,.dimy= 18,.id=PLEDIT_ADD_DIR_BUTTON_PRESSED},
	{.source=PLEDIT_BMP,  .startx=   54,.starty=  130,.dimx= 22,.dimy= 18,.id=PLEDIT_CROP_BUTTON_UNPRESSED},
	{.source=PLEDIT_BMP,  .startx=   77,.starty=  130,.dimx= 22,.dimy= 18,.id=PLEDIT_CROP_BUTTON_PRESSED},
	{.source=PLEDIT_BMP,  .startx=  104,.starty=  130,.dimx= 22,.dimy= 18,.id=PLEDIT_SELECT_NONE_BUTTON_UNPRESSED},
	{.source=PLEDIT_BMP,  .startx=  127,.starty=  130,.dimx= 22,.dimy= 18,.id=PLEDIT_SELECT_NONE_BUTTON_PRESSED},
	{.source=PLEDIT_BMP,  .startx=  154,.starty=  130,.dimx= 22,.dimy= 18,.id=PLEDIT_FILE_INFO_BUTTON_UNPRESSED},
	{.source=PLEDIT_BMP,  .startx=  177,.starty=  130,.dimx= 22,.dimy= 18,.id=PLEDIT_FILE_INFO_BUTTON_PRESSED},
	{.source=PLEDIT_BMP,  .startx=  204,.starty=  130,.dimx= 22,.dimy= 18,.id=PLEDIT_SAVE_LIST_BUTTON_UNPRESSED},
	{.source=PLEDIT_BMP,  .startx=  227,.starty=  130,.dimx= 22,.dimy= 18,.id=PLEDIT_SAVE_LIST_BUTTON_PRESSED},
	{.source=PLEDIT_BMP,  .startx=    0,.starty=  149,.dimx= 22,.dimy= 18,.id=PLEDIT_ADD_FILE_BUTTON_UNPRESSED},
	{.source=PLEDIT_BMP,  .startx=   23,.starty=  149,.dimx= 22,.dimy= 18,.id=PLEDIT_ADD_FILE_BUTTON_PRESSED},
	{.source=PLEDIT_BMP,  .startx=   54,.starty=  149,.dimx= 22,.dimy= 18,.id=PLEDIT_REMOVE_FILE_BUTTON_UNPRESSED},
	{.source=PLEDIT_BMP,  .startx=   77,.starty=  149,.dimx= 22,.dimy= 18,.id=PLEDIT_REMOVE_FILE_BUTTON_PRESSED},
	{.source=PLEDIT_BMP,  .startx=  104,.starty=  149,.dimx= 22,.dimy= 18,.id=PLEDIT_SELECT_ALL_BUTTON_UNPRESSED},
	{.source=PLEDIT_BMP,  .startx=  127,.starty=  149,.dimx= 22,.dimy= 18,.id=PLEDIT_SELECT_ALL_BUTTON_PRESSED},
	{.source=PLEDIT_BMP,  .startx=  154,.starty=  149,.dimx= 22,.dimy= 18,.id=PLEDIT_MISC_OPTIONS_BUTTON_UNPRESSED},
	{.source=PLEDIT_BMP,  .startx=  177,.starty=  149,.dimx= 22,.dimy= 18,.id=PLEDIT_MISC_OPTIONS_BUTTON_PRESSED},
	{.source=PLEDIT_BMP,  .startx=  204,.starty=  149,.dimx= 22,.dimy= 18,.id=PLEDIT_LOAD_LIST_BUTTON_UNPRESSED},
	{.source=PLEDIT_BMP,  .startx=  227,.starty=  149,.dimx= 22,.dimy= 18,.id=PLEDIT_LOAD_LIST_BUTTON_PRESSED},
	{.source=PLEDIT_BMP,  .startx=   54,.starty=  168,.dimx= 22,.dimy= 18,.id=PLEDIT_MISC_REMOVE_BUTTON_UNPRESSED},
	{.source=PLEDIT_BMP,  .startx=   77,.starty=  168,.dimx= 22,.dimy= 18,.id=PLEDIT_MISC_REMOVE_BUTTON_PRESSED},

// from posbar.bmp
	{.source=POSBAR_BMP,  .startx=    0,.starty=    0,.dimx=248,.dimy= 10,.id=POSBAR_SONG_PROGRESS_BAR},
	{.source=POSBAR_BMP,  .startx=  248,.starty=    0,.dimx= 29,.dimy= 10,.id=POSBAR_SONG_SLIDER_UNPRESSED},
	{.source=POSBAR_BMP,  .startx=  278,.starty=    0,.dimx= 29,.dimy= 10,.id=POSBAR_SONG_SLIDER_PRESSED},

// from shufrep.bmp
	{.source=SHUFREP_BMP, .startx=    0,.starty=    0,.dimx= 28,.dimy= 15,.id=SHUFREP_NO_REPEAT_UNPRESSED},
	{.source=SHUFREP_BMP, .startx=   28,.starty=    0,.dimx= 47,.dimy= 15,.id=SHUFREP_NO_SHUFFLE_UNPRESSED},
	{.source=SHUFREP_BMP, .startx=    0,.starty=   15,.dimx= 28,.dimy= 15,.id=SHUFREP_NO_REPEAT_PRESSED},
	{.source=SHUFREP_BMP, .startx=   28,.starty=   15,.dimx= 47,.dimy= 15,.id=SHUFREP_NO_SHUFFLE_PRESSED},
	{.source=SHUFREP_BMP, .startx=    0,.starty=   30,.dimx= 28,.dimy= 15,.id=SHUFREP_REPEAT_UNPRESSED},
	{.source=SHUFREP_BMP, .startx=   28,.starty=   30,.dimx= 47,.dimy= 15,.id=SHUFREP_SHUFFLE_UNPRESSED},
	{.source=SHUFREP_BMP, .startx=    0,.starty=   45,.dimx= 28,.dimy= 15,.id=SHUFREP_REPEAT_PRESSED},
	{.source=SHUFREP_BMP, .startx=   28,.starty=   45,.dimx= 47,.dimy= 15,.id=SHUFREP_SHUFFLE_PRESSED},
	{.source=SHUFREP_BMP, .startx=    0,.starty=   61,.dimx= 23,.dimy= 12,.id=SHUFREP_NO_EQUALIZER_UNPRESSED},
	{.source=SHUFREP_BMP, .startx=   23,.starty=   61,.dimx= 23,.dimy= 12,.id=SHUFREP_NO_PLAYLIST_UNPRESSED},
	{.source=SHUFREP_BMP, .startx=   46,.starty=   61,.dimx= 23,.dimy= 12,.id=SHUFREP_NO_EQUALIZER_PRESSED},
	{.source=SHUFREP_BMP, .startx=   69,.starty=   61,.dimx= 23,.dimy= 12,.id=SHUFREP_NO_PLAYLIST_PRESSED},
	{.source=SHUFREP_BMP, .startx=    0,.starty=   73,.dimx= 23,.dimy= 12,.id=SHUFREP_EQUALIZER_UNPRESSED},
	{.source=SHUFREP_BMP, .startx=   23,.starty=   73,.dimx= 23,.dimy= 12,.id=SHUFREP_PLAYLIST_UNPRESSED},
	{.source=SHUFREP_BMP, .startx=   46,.starty=   73,.dimx= 23,.dimy= 12,.id=SHUFREP_EQUALIZER_PRESSED},
	{.source=SHUFREP_BMP, .startx=   69,.starty=   73,.dimx= 23,.dimy= 12,.id=SHUFREP_PLAYLIST_PRESSED},

// from text.bmp
	{.source=TEXT_BMP,    .startx=    0,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_A},
	{.source=TEXT_BMP,    .startx=    5,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_B},
	{.source=TEXT_BMP,    .startx=   10,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_C},
	{.source=TEXT_BMP,    .startx=   15,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_D},
	{.source=TEXT_BMP,    .startx=   10,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_E},
	{.source=TEXT_BMP,    .startx=   20,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_F},
	{.source=TEXT_BMP,    .startx=   25,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_G},
	{.source=TEXT_BMP,    .startx=   30,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_H},
	{.source=TEXT_BMP,    .startx=   35,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_I},
	{.source=TEXT_BMP,    .startx=   40,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_J},
	{.source=TEXT_BMP,    .startx=   45,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_K},
	{.source=TEXT_BMP,    .startx=   50,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_L},
	{.source=TEXT_BMP,    .startx=   50,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_M},
	{.source=TEXT_BMP,    .startx=   60,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_N},
	{.source=TEXT_BMP,    .startx=   60,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_O},
	{.source=TEXT_BMP,    .startx=   70,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_P},
	{.source=TEXT_BMP,    .startx=   70,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_Q},
	{.source=TEXT_BMP,    .startx=   80,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_R},
	{.source=TEXT_BMP,    .startx=   80,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_S},
	{.source=TEXT_BMP,    .startx=   90,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_T},
	{.source=TEXT_BMP,    .startx=   90,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_U},
	{.source=TEXT_BMP,    .startx=  100,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_V},
	{.source=TEXT_BMP,    .startx=  100,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_W},
	{.source=TEXT_BMP,    .startx=  110,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_X},
	{.source=TEXT_BMP,    .startx=  110,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_Y},
	{.source=TEXT_BMP,    .startx=  120,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_Z},
	{.source=TEXT_BMP,    .startx=  130,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_QUOTATION_MARK},
	{.source=TEXT_BMP,    .startx=  135,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_AT_SYMBOL},
	{.source=TEXT_BMP,    .startx=  142,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_TIME_DISPLAY_BACKGROUND},
	{.source=TEXT_BMP,    .startx=  150,.starty=    0,.dimx=  5,.dimy=  6,.id=TEXT_TITLE_DISPLAY_SPACE},
	{.source=TEXT_BMP,    .startx=    0,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_0},
	{.source=TEXT_BMP,    .startx=    5,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_1},
	{.source=TEXT_BMP,    .startx=   10,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_2},
	{.source=TEXT_BMP,    .startx=   15,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_3},
	{.source=TEXT_BMP,    .startx=   20,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_4},
	{.source=TEXT_BMP,    .startx=   25,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_5},
	{.source=TEXT_BMP,    .startx=   30,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_6},
	{.source=TEXT_BMP,    .startx=   35,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_7},
	{.source=TEXT_BMP,    .startx=   40,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_8},
	{.source=TEXT_BMP,    .startx=   45,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_9},
	{.source=TEXT_BMP,    .startx=   50,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_ELLIPSIS},
	{.source=TEXT_BMP,    .startx=   55,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_PERIOD},
	{.source=TEXT_BMP,    .startx=   60,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_COLON},
	{.source=TEXT_BMP,    .startx=   65,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_LEFT_PARENTHESIS},
	{.source=TEXT_BMP,    .startx=   70,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_RIGHT_PARENTHESIS},
	{.source=TEXT_BMP,    .startx=   75,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_DASH},
	{.source=TEXT_BMP,    .startx=   80,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_APOSTROPHE},
	{.source=TEXT_BMP,    .startx=   85,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_EXCLAMATION_MARK},
	{.source=TEXT_BMP,    .startx=   90,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_UNDERSCORE},
	{.source=TEXT_BMP,    .startx=   95,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_PLUS_SYMBOL},
	{.source=TEXT_BMP,    .startx=  100,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_BACK_SLASH},
	{.source=TEXT_BMP,    .startx=  105,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_SLASH},
	{.source=TEXT_BMP,    .startx=  110,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_LEFT_BRACKET},
	{.source=TEXT_BMP,    .startx=  115,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_RIGHT_BRACKET},
	{.source=TEXT_BMP,    .startx=  120,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_CARROT},
	{.source=TEXT_BMP,    .startx=  125,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_AMPERSAND},
	{.source=TEXT_BMP,    .startx=  130,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_PERCENT},
	{.source=TEXT_BMP,    .startx=  135,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_COMMA},
	{.source=TEXT_BMP,    .startx=  140,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_EQUAL},
	{.source=TEXT_BMP,    .startx=  145,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_DOLLAR},
	{.source=TEXT_BMP,    .startx=  150,.starty=    6,.dimx=  5,.dimy=  6,.id=TEXT_POUND},
	{.source=TEXT_BMP,    .startx=    0,.starty=   12,.dimx=  5,.dimy=  6,.id=TEXT_A_CIRCUMFLEX},
	{.source=TEXT_BMP,    .startx=    5,.starty=   12,.dimx=  5,.dimy=  6,.id=TEXT_O_UMLAUT},
	{.source=TEXT_BMP,    .startx=   10,.starty=   12,.dimx=  5,.dimy=  6,.id=TEXT_A_UMLAUT},
	{.source=TEXT_BMP,    .startx=   15,.starty=   12,.dimx=  5,.dimy=  6,.id=TEXT_QUESTION_MARK},
	{.source=TEXT_BMP,    .startx=   20,.starty=   12,.dimx=  5,.dimy=  6,.id=TEXT_ASTERISK},
	{.source=TEXT_BMP,    .startx=  100,.starty=   12,.dimx=  5,.dimy=  6,.id=TEXT_KBPS_DISPLAY_SPACE},

// from titlebar.bmp
	{.source=TITLEBAR_BMP,.startx=    0,.starty=    0,.dimx=  9,.dimy=  9,.id=TITLEBAR_MENU_BUTTON_UNPRESSED},
	{.source=TITLEBAR_BMP,.startx=    9,.starty=    0,.dimx=  9,.dimy=  9,.id=TITLEBAR_MINIMIZE_BUTTON_UNPRESED},
	{.source=TITLEBAR_BMP,.startx=   18,.starty=    0,.dimx=  9,.dimy=  9,.id=TITLEBAR_EXIT_BUTTON_UNPRESSED},
	{.source=TITLEBAR_BMP,.startx=   27,.starty=    0,.dimx=275,.dimy= 14,.id=TITLEBAR_NORMAL_TITLEBAR_ACTIVE},
	{.source=TITLEBAR_BMP,.startx=  304,.starty=    0,.dimx=  8,.dimy= 43,.id=TITLEBAR_CLUTTERBAR_SHOWN},
	{.source=TITLEBAR_BMP,.startx=  312,.starty=    0,.dimx=  8,.dimy= 43,.id=TITLEBAR_CLUTTERBAR_HIDDEN},
	{.source=TITLEBAR_BMP,.startx=    0,.starty=    9,.dimx=  9,.dimy=  9,.id=TITLEBAR_MENU_BUTTON_PRESSED},
	{.source=TITLEBAR_BMP,.startx=    9,.starty=    9,.dimx=  9,.dimy=  9,.id=TITLEBAR_MINIMIZE_BUTTON_PRESSED},
	{.source=TITLEBAR_BMP,.startx=   18,.starty=    9,.dimx=  9,.dimy=  9,.id=TITLEBAR_EXIT_BUTTON_PRESSED},
	{.source=TITLEBAR_BMP,.startx=   27,.starty=   15,.dimx=275,.dimy= 14,.id=TITLEBAR_NORMAL_TITLEBAR_INACTIVE},
	{.source=TITLEBAR_BMP,.startx=    0,.starty=   18,.dimx=  9,.dimy=  9,.id=TITLEBAR_WINDOWSHADE_BUTTON_UNPRESSED},
	{.source=TITLEBAR_BMP,.startx=    9,.starty=   18,.dimx=  9,.dimy=  9,.id=TITLEBAR_WINDOWSHADE_BUTTON_PRESSED},
	{.source=TITLEBAR_BMP,.startx=    0,.starty=   27,.dimx=  9,.dimy=  9,.id=TITLEBAR_MAXIMIZE_BUTTON_UNPRESSED},
	{.source=TITLEBAR_BMP,.startx=    9,.starty=   27,.dimx=  9,.dimy=  9,.id=TITLEBAR_MAXIMIZE_BUTTON_PRESSED},
	{.source=TITLEBAR_BMP,.startx=   27,.starty=   29,.dimx=275,.dimy= 14,.id=TITLEBAR_WINDOWSHADE_TITLEBAR_ACTIVE},
	{.source=TITLEBAR_BMP,.startx=    0,.starty=   36,.dimx= 17,.dimy=  7,.id=TITLEBAR_SONG_PROGRESS_BAR},
	{.source=TITLEBAR_BMP,.startx=   17,.starty=   36,.dimx=  9,.dimy=  7,.id=TITLEBAR_SONG_PROGRESS_CONTROLS},
	{.source=TITLEBAR_BMP,.startx=   27,.starty=   42,.dimx=275,.dimy= 14,.id=TITLEBAR_WINDOWSHADE_TITLEBAR_INACTIVE},
	{.source=TITLEBAR_BMP,.startx=  304,.starty=   44,.dimx=  8,.dimy= 43,.id=TITLEBAR_CLUTTERBAR_O_PRESSED},
	{.source=TITLEBAR_BMP,.startx=  312,.starty=   44,.dimx=  8,.dimy= 43,.id=TITLEBAR_CLUTTERBAR_A_PRESSED},
	{.source=TITLEBAR_BMP,.startx=  320,.starty=   44,.dimx=  8,.dimy= 43,.id=TITLEBAR_CLUTTERBAR_I_PRESSED},
	{.source=TITLEBAR_BMP,.startx=  328,.starty=   44,.dimx=  8,.dimy= 43,.id=TITLEBAR_CLUTTERBAR_D_PRESSED},
	{.source=TITLEBAR_BMP,.startx=  336,.starty=   44,.dimx=  8,.dimy= 43,.id=TITLEBAR_CLUTTERBAR_V_PRESSED},
	{.source=TITLEBAR_BMP,.startx=   27,.starty=   57,.dimx=275,.dimy=114,.id=TITLEBAR_ALTERNATIVE_TITLEBAR_ACTIVE},
	{.source=TITLEBAR_BMP,.startx=   27,.starty=   72,.dimx=275,.dimy=114,.id=TITLEBAR_ALTERNATIVE_TITLEBAR_INACTIVE},

// from volume.bmp
	{.source=VOLUME_BMP,  .startx=    0,.starty=    0,.dimx= 68,.dimy= 13,.id=VOLUME_000_001},
	{.source=VOLUME_BMP,  .startx=    0,.starty=   15,.dimx= 68,.dimy= 13,.id=VOLUME_003_005},
	{.source=VOLUME_BMP,  .startx=    0,.starty=   30,.dimx= 68,.dimy= 13,.id=VOLUME_007_009},
	{.source=VOLUME_BMP,  .startx=    0,.starty=   45,.dimx= 68,.dimy= 13,.id=VOLUME_011_013},
	{.source=VOLUME_BMP,  .startx=    0,.starty=   60,.dimx= 68,.dimy= 13,.id=VOLUME_015_017},
	{.source=VOLUME_BMP,  .startx=    0,.starty=   75,.dimx= 68,.dimy= 13,.id=VOLUME_019_021},
	{.source=VOLUME_BMP,  .startx=    0,.starty=   90,.dimx= 68,.dimy= 13,.id=VOLUME_023_025},
	{.source=VOLUME_BMP,  .startx=    0,.starty=  105,.dimx= 68,.dimy= 13,.id=VOLUME_027_029},
	{.source=VOLUME_BMP,  .startx=    0,.starty=  120,.dimx= 68,.dimy= 13,.id=VOLUME_031},
	{.source=VOLUME_BMP,  .startx=    0,.starty=  135,.dimx= 68,.dimy= 13,.id=VOLUME_033_035},
	{.source=VOLUME_BMP,  .startx=    0,.starty=  150,.dimx= 68,.dimy= 13,.id=VOLUME_037_039},
	{.source=VOLUME_BMP,  .startx=    0,.starty=  165,.dimx= 68,.dimy= 13,.id=VOLUME_041_043},
	{.source=VOLUME_BMP,  .startx=    0,.starty=  180,.dimx= 68,.dimy= 13,.id=VOLUME_045_047},
	{.source=VOLUME_BMP,  .startx=    0,.starty=  195,.dimx= 68,.dimy= 13,.id=VOLUME_049_050},
	{.source=VOLUME_BMP,  .startx=    0,.starty=  210,.dimx= 68,.dimy= 13,.id=VOLUME_052_054},
	{.source=VOLUME_BMP,  .startx=    0,.starty=  225,.dimx= 68,.dimy= 13,.id=VOLUME_056_058},
	{.source=VOLUME_BMP,  .startx=    0,.starty=  240,.dimx= 68,.dimy= 13,.id=VOLUME_060_062},
	{.source=VOLUME_BMP,  .startx=    0,.starty=  255,.dimx= 68,.dimy= 13,.id=VOLUME_064},
	{.source=VOLUME_BMP,  .startx=    0,.starty=  270,.dimx= 68,.dimy= 13,.id=VOLUME_066_068},
	{.source=VOLUME_BMP,  .startx=    0,.starty=  285,.dimx= 68,.dimy= 13,.id=VOLUME_070_072},
	{.source=VOLUME_BMP,  .startx=    0,.starty=  300,.dimx= 68,.dimy= 13,.id=VOLUME_074_076},
	{.source=VOLUME_BMP,  .startx=    0,.starty=  315,.dimx= 68,.dimy= 13,.id=VOLUME_078_080},
	{.source=VOLUME_BMP,  .startx=    0,.starty=  330,.dimx= 68,.dimy= 13,.id=VOLUME_082_084},
	{.source=VOLUME_BMP,  .startx=    0,.starty=  345,.dimx= 68,.dimy= 13,.id=VOLUME_086_088},
	{.source=VOLUME_BMP,  .startx=    0,.starty=  360,.dimx= 68,.dimy= 13,.id=VOLUME_090_092},
	{.source=VOLUME_BMP,  .startx=    0,.starty=  375,.dimx= 68,.dimy= 13,.id=VOLUME_094_096},
	{.source=VOLUME_BMP,  .startx=    0,.starty=  390,.dimx= 68,.dimy= 13,.id=VOLUME_098},
	{.source=VOLUME_BMP,  .startx=    0,.starty=  405,.dimx= 68,.dimy= 13,.id=VOLUME_100},
	{.source=VOLUME_BMP,  .startx=    0,.starty=  422,.dimx= 14,.dimy= 11,.id=VOLUME_SLIDER_PRESSED},
	{.source=VOLUME_BMP,  .startx=   15,.starty=  422,.dimx= 14,.dimy= 11,.id=VOLUME_SLIDER_UNPRESSED}
		
};
